visual_slam:
  ros__parameters:

    num_cameras: 2
    min_num_images: 2
    
    enable_imu_fusion: true
    gyro_noise_density: 0.000244
    gyro_random_walk: 0.000019393
    accel_noise_density: 0.001862
    accel_random_walk: 0.003
    calibration_frequency: 200.0
    
    enable_localization_n_mapping: true
    enable_planar_mode: false
    
    rectified_images: true
    denoise_input_images: false
    
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    camera_optical_frames: 
      - "nfra1_optical_frame"
      - "infra2_optical_frame"
    imu_frame: "imu_optical_frame"
    
    enable_slam_visualization: true
    enable_landmarks_view: true
    enable_observations_view: true
    path_max_size: 1000
    
    enable_debug_mode: false
    debug_dump_path: "/tmp/cuvslam"
    verbosity: 3