diagnostic_aggregator:
  ros__parameters:
    pub_rate: 1.0  # Hz
    
    analyzers:
      # CPU 
      system:
        type: "diagnostic_aggregator/GenericAnalyzer"
        path: "System"
        contains: ['system_load', 'cpu_usage', 'memory_usage']
        
      # RealSense
      realsense:
        type: "diagnostic_aggregator/GenericAnalyzer"
        path: "Sensors"
        contains: ['realsense_d435i'] 